name: Name
description: Description
branding:
  icon: activity
  color: blue

inputs:
  example:
    description: Example Input
    required: false
  
runs:
  using: composite
  steps:

    - shell: bash
      env:
        EXAMPLE: ${{ inputs.example }}
      run: |
        echo 'Hello, World!'
