name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Action
        uses: ./
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          procedures: |
            [
              {
                "name": "Example",
                "tasks": ["Task A", "Task B", "Task C"]
              }
            ]
          event-issue-number: -1
          event-issue-title: Example
          event-name: issues
